UrlShortener/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shorty.urls')),
]

shorty/urls.py
from django.urls import path
from .views import home, redirect_url_view

appname='shorty'

urlpatterns = [
    path("",home, name='home'),
    path('<str:shortened_part>', redirect_url_view, name='redirect')
]

shorty/models.py
from django.db import models
from .utils import create_shortened_url

# Create your models here.
class Url(models.Model):
    long_url=models.URLField()
    short_url=models.CharField(max_length=15, unique=True, blank=True)
    date=models.DateTimeField(auto_now_add=True)
    click=models.PositiveIntegerField(default=0)

    class Meta:
        ordering=["-date"]

    def __str__(self):
        return f'{self.long_url} to {self.short_url}'

    def save(self, *args, **kwargs):
        # if the short url wasn't specified
        if not self.short_url:
            # we pass the model instance that is being saved
            self.short_url=create_shortened_url(self)

        super().save(*args, **kwargs)

shorty/forms.py
from django import forms
from .models import Url

class ShortenerForm(forms.ModelForm):
    long_url=forms.URLField(widget=forms.URLInput(
        attrs={'class':"form-control form-control-lg", "placeholder":"Your URL to shorten"}))

    class Meta:
        model=Url
        fields=('long_url',)

shorty/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from .models import Url
from .forms import ShortenerForm

# Create your views here.
def home(request):
    templates='shorty/home.html'

    context={}

    # Empty form
    context['form']=ShortenerForm()

    if request.method=='GET':
        return render(request, templates, context)
    elif request.method=='POST':
        used_form=ShortenerForm(request.POST)

        if used_form.is_valid():

            shortened_object=used_form.save()
            new_url=request.build_absolute_uri('/') + shortened_object.short_url
            long_url=shortened_object.long_url

            context['new_url']=new_url
            context['long_url']=long_url

            return render(request, templates, context)

        context['errors']=used_form.errors

        return render(request, templates, context)

def redirect_url_view(request, shortened_part):

    try:
        shortener=Url.objects.get(short_url=shortened_part)

        shortener.click+=1
        shortener.save()

        return HttpResponseRedirect(shortener.long_url)
    except:
        raise Http404('Sorry this link is broken :(')

shorty/templates/shorty/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
     integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Url Shortener</title>
    <style>
        h1 {
            text-align: center;
        }

        .card {
            display: grid;
            justify-content: center;
            align-content: center;
            background-color: rgb(219, 215, 213);
            border-radius: 5px;
        }

        .row {
            display: flex;
            justify-content: center;
            align-content: center;
            padding: 30px;
        }

        #content {
            background-color: rgb(213, 216, 219);
            display: grid;
            justify-content: center;
            align-content: center;
            margin-top: 20px;
        }

        #id_long_url {
            width: 500px;
            height: 50px;
            border: none;
        }

        @media only screen and(max-width: 600px) {
            #id_long_url{
                width:inherit;
            }
        }

        .btn {
            width: 100px;
            height: 35px;
            margin-left: -20px;
            margin-top: 9px;
            border: none;
            border-radius: 3px;
        }

        .btn:hover, .btn:focus {
            background-color: black;
            color: white;
        }
    </style>
</head>

<body>
    <div class="card-hearder text-center py-3">
        <h1>Url Shortener <i class="fas fa-link px-2"></i></h1>
    </div>
    <div class="center">
        <div class="card mt-5">
            <form action="" method="POST">
                {% csrf_token %}
                <div class="row g-1">
                    <div class="col-md-10">{{form.long_url}}</div>
                    <div class="col-2">
                        <button class="btn btn-success btn-lg w-100" type="submit">Shorten</button>
                    </div>
                </div>
            </form>
        </div>
        {% if errors %}
        <div class="alert alert-danger mt-4" role="alert">
            <p>{{errors}}</p>
        </div>
        {% endif %}

        {% if new_url %}
        <div class="mx-auto text-center mt-5" id="content">
            <h2 class="text-danger" style="text-align: center;">Your Shortened Url</h2>
            <p>You can copy the link below and share it with your friends</p>
            <p class="">{{new_url}}</p>
            <p><span class="text-danger">Previous URL:</span>{{long_url}}</p>
        </div>
        {% endif %}
    </div>
</body>

</html>